------------------------------------------------------------
-- V3 : 영화 상영 시간 데이터 추가
------------------------------------------------------------

INSERT INTO running_time (movie_id, cinema_id, screen_number, start_time)
VALUES
    (1, 1, 1, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (1, 1, 2, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (1, 1, 3, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (1, 2, 1, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (1, 2, 2, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (1, 2, 3, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (1, 3, 1, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (1, 3, 2, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (1, 3, 3, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),

    (2, 1, 1, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (2, 1, 2, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (2, 1, 3, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (2, 2, 1, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (2, 2, 2, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (2, 2, 3, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (2, 3, 1, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (2, 3, 2, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (2, 3, 3, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),

    (3, 1, 1, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (3, 1, 2, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (3, 1, 3, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (3, 2, 1, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (3, 2, 2, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (3, 2, 3, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (3, 3, 1, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (3, 3, 2, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (3, 3, 3, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),

    (4, 1, 1, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (4, 1, 2, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (4, 1, 3, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (4, 2, 1, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (4, 2, 2, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (4, 2, 3, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (4, 3, 1, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (4, 3, 2, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE)))),
    (4, 3, 3, TIMESTAMPADD(SECOND,-SECOND(CURRENT_TIMESTAMP), TIMESTAMPADD(MINUTE, (FLOOR(RANDOM() * 6) * 10), TIMESTAMPADD(HOUR, FLOOR(RANDOM() * 24), CURRENT_DATE))));